spring.application.name=student-management
server.port=${PORT:8080}

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/student_management}
spring.datasource.username=${DB_USERNAME:student}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection string
#jdbc:postgresql://neondb_owner:npg_M3ANq4mTdZBY@ep-delicate-poetry-a1b625m5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require